### ISSUE TITLE
Logging for python n00bs

### ISSUE THREAD

**Issue by swissdave** [brutasse/graphite-api#118]
Hi there,
I'm trying to write a custom finder etc using graphite-api and all looks good util I get an exception from a render call.  I get a 500 back to the browser:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

and in the Apache log:
[Fri Jul 10 15:17:13 2015] [error] No handlers could be found for logger "flask.app"

Is there a simple way to find out what the problem is?  I'm using graphite-api 1.0.1 via pip (can't get install from source to work)

Thanks

**Comment by swissdave** [comment]
I added this to the config, but still nothing in the apache log or /var/log/graphite-api.log (file is empty)

```
logging:
  version: 1
  handlers:
    raw:
      level: DEBUG
      class: logging.StreamHandler
      formatter: raw
  loggers:
    root:
      handlers:
        - raw
      level: DEBUG
      propagate: false
    graphite_api:
      handlers:
        - raw
      level: DEBUG
```
