### ISSUE TITLE
can't have curent metrics

### ISSUE THREAD

**Issue by adnane-** [brutasse/graphite-api#17]
curl http://ip:8000/render?target=collectd.ip.memory.memory-used&format=csv&from=-3h
collectd.ip.memory.memory-used,2014-04-18 10:01:50,247963648.0
collectd.ip.memory.memory-used,2014-04-18 10:02:00,249802752.0
collectd.ip.memory.memory-used,2014-04-18 10:03:30,225345536.0
collectd.ip.memory.memory-used,2014-04-18 10:03:40,227315712.0
collectd.ip.memory.memory-used,2014-04-18 10:05:30,249901056.0
collectd.ip.memory.memory-used,2014-04-18 10:10:40,244023296.0
collectd.ip.memory.memory-used,2014-04-18 10:10:50,246218752.0
collectd.ip.memory.memory-used,2014-04-18 10:11:00,246341632.0
collectd.ip.memory.memory-used,2014-04-18 10:11:10,224964608.0
collectd.ip.memory.memory-used,2014-04-18 10:11:20,225087488.0
collectd.ip.memory.memory-used,2014-04-18 10:11:30,
collectd.ip.memory.memory-used,2014-04-18 10:11:40,
collectd.ip.memory.memory-used,2014-04-18 11:06:50,
collectd.ip.memory.memory-used,2014-04-18 11:07:00,
collectd.ip.memory.memory-used,2014-04-18 11:07:10,
collectd.ip.memory.memory-used,2014-04-18 11:07:20,
collectd.ip.memory.memory-used,2014-04-18 11:10:20,
collectd.ip.memory.memory-used,2014-04-18 11:10:30,
collectd.ip.memory.memory-used,2014-04-18 11:10:40,
collectd.ip.memory.memory-used,2014-04-18 11:10:50,
collectd.ip.memory.memory-used,2014-04-18 11:11:00,
collectd.ip.memory.memory-used,2014-04-18 11:11:10,
collectd.ip.memory.memory-used,2014-04-18 11:11:20,
collectd.ip.memory.memory-used,2014-04-18 11:11:30,
date
Fri Apr 18 12:13:09 CEST 2014

I use cyanite to store data here is the config file of cyanite

```
carbon:
  host: "0.0.0.0"
  port: 2003
  rollups:
    - period: 3600
      rollup: 10
http:
  host: "0.0.0.0"
  port: 8080
logging:
  level: info
  console: true
  files:
    - "/tmp/cyanite.log"
store:
  cluster: 'localhost'
  keyspace: 'metric'
```

I don(t understand why I can't have curent metrics, can any one help please
