### ISSUE TITLE
Connection reset by peer from Carbon host

### ISSUE THREAD

**Issue by sevagh** [brutasse/graphite-api#236]
Hello, I'm trying to switch from using `graphite-web` to `graphite-api`. I'm running the version from apt repos on Debian 9:

```shell
$ dpkg -l | grep graphite-api
ii  graphite-api                       1.1.3-2                        all          Enterprise Scalable Realtime Graphing (API-only frontend)
```

I have carbon running on the same host. These are the graphite-web settings for carbon:

```python
CARBONLINK_HOSTS = ["127.0.0.1:7035:00"]
CARBONLINK_TIMEOUT = 15.0
CARBONLINK_RETRY_DELAY = 15 # Seconds to blacklist a failed remote server
```

These are my graphite-api.yml settings:

```
shanssian@huey:~$ sudo cat /etc/graphite-api.yaml
search_index: /var/lib/graphite-api/index
finders:
  - graphite_api.finders.whisper.WhisperFinder
whisper:
  directories:
    - /var/lib/graphite/storage/whisper
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
carbon:
  hosts:
    - 127.0.0.1:7035:00
  timeout: 15
  retry_delay: 15
  carbon_prefix: carbon
  replication_factor: 1
allowed_origins:
  - '*'
```
In the logs I get `Connection reset by peer` when it tries to fetch Carbon stats:
```
Apr 17 09:20:45 srvr1 gunicorn3[94161]: {"host": "('127.0.0.1', '00')", "event": "carbonlink exception", "exception": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/graphite_api/carbonlink.py\", line 235, in send_request\n    result = self.recv_response(conn)\n  File \"/usr/lib/python3/dist-packages/graphite_api/carbonlink.py\", line 280, in recv_response\n    len_prefix = recv_exactly(conn, 4)\n  File \"/usr/lib/python3/dist-packages/graphite_api/carbonlink.py\", line 312, in recv_exactly\n    data = conn.recv(num_bytes - len(buf))\nConnectionResetError: [Errno 104] Connection reset by peer"}
```
Am I configuring something wrong? I can telnet to `127.0.0.1 7035` just fine - graphite-web is able to interact with Carbon.

Thanks.
