### ISSUE TITLE
how to make the log work

### ISSUE THREAD

**Issue by liyichao** [brutasse/graphite-api#93]
The log config makes me confused. I also try to turn on debug in graphite-api.yaml, but no extra logs have been printed.

I doubt whether structured log makes graphite-api good. Because the log system now seems useless.

**Comment by brutasse** [comment]
That doesn't have anything to do with structured logging. Which version are you running? Master or 1.0.1? There's relatively little logging in 1.0.1.

You can configure logging with the following structure:

```yaml
logging:
  version: 1
  handlers:
    raw:
      level: DEBUG
      class: logging.StreamHandler
      formatter: raw
  loggers:
    root:
      handlers:
        - raw
      level: DEBUG
      propagate: false
    graphite_api:
      handlers:
        - raw
      level: DEBUG
```
